# Generated by Django 5.0.1 on 2024-02-06 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="id_user",
        ),
        migrations.AddField(
            model_name="profile",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("0", "None"),
                    ("1", "Single"),
                    ("2", "In a relationship"),
                    ("3", "Married"),
                    ("4", "Engaged"),
                ],
                default="0",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="working_at",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
