# Generated by Django 5.0.1 on 2024-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_profile_id_user_profile_relationship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_user",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
