# Generated by Django 5.0.1 on 2024-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_profile_id_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default=5, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default=5, max_length=55),
            preserve_default=False,
        ),
    ]
